### ISSUE TITLE
CSS Inheritence

### ISSUE THREAD

**Issue by cyouh95** [lerankine94/prj-rev-bwfs-dasmoto#3]
For universally shared properties, such as `font-family: Helvetica`, you could use `body` as the selector. All its children elements would then automatically inherit this property without you needing to specify it individually for each:

```css
body {
  font-family: Helvetica;
}
```
