### ISSUE TITLE
Comma-separated selectors

### ISSUE THREAD

**Issue by cyouh95** [lerankine94/prj-rev-bwfs-dasmoto#4]
Alternatively, you could use comma-separated selectors to specify shared properties among multiple elements:

```css
h1, h2, h3, .blue {
  font-weight: bold;
}
```
